/**Create the necessary data structures to contain the data specified in the Appendix ensuring that data integrity is enforced**/
CREATE TABLE departments (
    dept_id   NUMBER(5),--GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
    dept_name VARCHAR2(50) NOT NULL,
    location  VARCHAR2(50) NOT NULL,
    PRIMARY KEY ( dept_id )
)
    PARTITION BY LIST ( location ) ( PARTITION part_london VALUES ( 'LONDON' ),
        PARTITION part_cardiff VALUES ( 'CARDIFF' ),
        PARTITION part_edinburgh VALUES ( 'EDINBURGH' ),
        PARTITION part_belfast VALUES ( 'BELFAST' ),
        PARTITION part_others VALUES ( DEFAULT )
    );

COMMENT ON COLUMN departments.dept_id IS
    'The Unique identifier for the department';

COMMENT ON COLUMN departments.dept_name IS
    'The name of the department';

COMMENT ON COLUMN departments.location IS
    'The physical location of the department';